/**
 * Channel names only (no zod) so the preload bundle stays tiny. The typed contracts in contract.ts and
 * events.ts must cover exactly these channels (enforced by the type checker).
 */
export const INVOKE_CHANNELS = [
  'app:getInfo',
  'app:getHostStatus',
  'app:readLegal',
  'settings:get',
  'settings:update',
  'settings:problems',
  'settings:openFile',
  'ui:getState',
  'ui:patchState',
  'ui:quickPickResult',
  'projects:list',
  'projects:getActive',
  'projects:add',
  'projects:remove',
  'projects:update',
  'projects:reorder',
  'projects:setActive',
  'projects:pickFolder',
  'terminals:create',
  'terminals:kill',
  'terminals:restart',
  'terminals:rename',
  'terminals:dispose',
  'terminals:list',
  'terminals:profiles',
  'shell:openExternal',
  'shell:revealInFolder',
  'clipboard:read',
  'clipboard:writeText',
  'terminals:clearBell',
  'agents:list',
  'projects:getActivity',
  'terminals:markSeen',
  'window:setAttention',
  'git:getStatus',
  'git:refresh',
  'git:getFileDiff',
  'plugins:list',
  'plugins:contributions',
  'plugins:setEnabled',
  'plugins:reload',
  'plugins:loadFromFolder',
  'plugins:removeDevPath',
  'plugins:openDevTools',
  'plugins:executeCommand',
  'plugins:logs',
  'plugins:activate',
  'plugins:viewOpened',
  'plugins:statusBar',
  'plugins:viewClosed',
  'plugins:viewVisibility',
  'plugins:viewMessage',
  'fs:statMany',
  'editor:open',
  'keybindings:get',
  'keybindings:setForCommand',
  'keybindings:openFile',
  'workspace:load',
  'workspace:save',
] as const;

export const EVENT_CHANNELS = [
  'settings:changed',
  'hosts:status',
  'terminals:updated',
  'terminals:removed',
  'agents:updated',
  'projects:changed',
  'projects:active',
  'notifications:show',
  'projects:activity',
  'terminals:reveal',
  'git:status',
  'git:fileTouched',
  'editor:openInTerminal',
  'plugins:changed',
  'plugins:contributionsChanged',
  'plugins:reloaded',
  'terminals:openPanel',
  'commands:run',
  'plugins:viewMessage',
  'plugins:viewMeta',
  'plugins:statusBar',
  'plugins:openPanel',
  'ui:quickPick',
  'keybindings:changed',
] as const;

export type InvokeChannel = (typeof INVOKE_CHANNELS)[number];
export type EventChannel = (typeof EVENT_CHANNELS)[number];
