import { execFileSync } from 'node:child_process';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { expect, type Page, test } from '@playwright/test';
import { launchApp, repoRoot } from './helpers/launch';
import { waitForTerminal } from './helpers/terminal';

const invoke = (win: Page, channel: string, payload?: unknown) =>
  win.evaluate(([c, p]) => window.oxy.invoke(c as never, p as never), [channel, payload] as const);

// M9-T4: a project from `create-oxytocin-plugin` (React template) runs in the app in developer mode.
test('a plugin generated by create-oxytocin-plugin loads, opens its panel and talks to its backend', async () => {
  test.setTimeout(120_000);
  await mkdir(join(repoRoot, 'node_modules/.cache'), { recursive: true });
  const work = await mkdtemp(join(repoRoot, 'node_modules/.cache/oxy-create-e2e-'));
  const dir = join(work, 'hello-world');
  // The CLI, as `npm create oxytocin-plugin` runs it.
  execFileSync(
    process.execPath,
    [
      join(repoRoot, 'packages/create-oxytocin-plugin/index.js'),
      dir,
      '--yes',
      '--id',
      'acme.hello-world',
      '--name',
      'Hello World',
      '--publisher',
      'acme',
      '--template',
      'react',
    ],
    { stdio: 'pipe' },
  );
  execFileSync(process.execPath, ['build.mjs'], { cwd: dir, stdio: 'pipe' });

  const userData = await mkdtemp(join(tmpdir(), 'oxy-e2e-'));
  await writeFile(
    join(userData, 'settings.json'),
    JSON.stringify({ 'plugins.developerMode': true, 'plugins.devPaths': [dir] }),
  );
  const project = join(await mkdtemp(join(tmpdir(), 'oxy-e2e-project-')), 'demo');
  await mkdir(project);
  const { app, win } = await launchApp({ userData, project });
  try {
    await waitForTerminal(win);
    const state = async () =>
      ((await invoke(win, 'plugins:list')) as { id: string; state: string }[]).find((p) => p.id === 'acme.hello-world')
        ?.state;
    await expect.poll(state, { timeout: 20_000 }).toBe('active');
    await expect(win.getByTestId('status-item-hello-world.status')).toContainText('Hello World');

    await win.keyboard.press('Control+Shift+KeyP');
    await win.keyboard.type('Hello World: Open');
    await win.keyboard.press('Enter');
    const frame = () => win.frames().find((f) => f.url().startsWith('oxy-plugin://acme.hello-world/'));
    await expect.poll(() => !!frame(), { timeout: 15_000 }).toBe(true);
    await frame()!.locator('#greet').click();
    await expect(frame()!.locator('#status')).toHaveText('Hello, Oxytocin! You have 1 project.');
    await frame()!.locator('#hello').click();
    await expect(
      win.locator('[data-sonner-toast]').filter({ hasText: 'Hello from Hello World in demo!' }),
    ).toBeVisible();
  } finally {
    await app.close();
    await rm(work, { recursive: true, force: true });
  }
});
