/**
 * Generates THIRD_PARTY_NOTICES.md from the licenses of production dependencies (ADR-020),
 * followed by manual entries for assets that do not come from npm.
 */
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

interface LicenseInfo {
  licenses?: string | string[];
  repository?: string;
  publisher?: string;
  licenseFile?: string;
}

const root = resolve(import.meta.dirname, '..');
const cli = join(root, 'node_modules/license-checker-rseidelsohn/bin/license-checker-rseidelsohn.js');
const raw = execFileSync(
  process.execPath,
  [cli, '--production', '--json', '--excludePrivatePackages', '--start', root],
  {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
  },
);
const packages = JSON.parse(raw) as Record<string, LicenseInfo>;

const manualEntries = join(root, 'resources/notices/manual.md');

const lines: string[] = [
  '# Third-Party Notices',
  '',
  'Oxytocin is licensed under the MIT License (see `LICENSE`). It includes the third-party software listed below.',
  'This file is generated by `npm run licenses:notices` — do not edit it by hand.',
  '',
];

for (const [name, info] of Object.entries(packages).sort(([a], [b]) => a.localeCompare(b))) {
  const license = Array.isArray(info.licenses) ? info.licenses.join(', ') : (info.licenses ?? 'UNKNOWN');
  lines.push(`## ${name}`, '', `- License: ${license}`);
  if (info.repository) lines.push(`- Repository: ${info.repository}`);
  lines.push('');
  if (info.licenseFile && existsSync(info.licenseFile) && !/readme/i.test(info.licenseFile)) {
    lines.push('```text', readFileSync(info.licenseFile, 'utf8').trim(), '```', '');
  }
}

if (existsSync(manualEntries)) {
  lines.push(readFileSync(manualEntries, 'utf8').trim(), '');
}

writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), lines.join('\n'));
console.log(`THIRD_PARTY_NOTICES.md: ${Object.keys(packages).length} packages`);
